const std = @import("std");
const generated = @import("generated_index.zig");

const testing = std.testing;
const default_round_trip_versions = [_]i16{
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
};

fn roundTripDefault(comptime Message: type, comptime version: i16) !void {
    var value = Message{};
    const size = value.calcSize(version);

    const buf = try testing.allocator.alloc(u8, size);
    defer testing.allocator.free(buf);

    var pos: usize = 0;
    value.serialize(buf, &pos, version);
    try testing.expectEqual(size, pos);

    var read_pos: usize = 0;
    const decoded = try Message.deserialize(testing.allocator, buf, &read_pos, version);
    try testing.expectEqual(pos, read_pos);
    try testing.expectEqual(size, decoded.calcSize(version));
}

fn roundTripDefaultVersions(comptime Message: type) !void {
    inline for (default_round_trip_versions) |version| {
        try roundTripDefault(Message, version);
    }
}

test "generated default messages round-trip across common protocol versions" {
    const messages = .{
        generated.add_offsets_to_txn_request.AddOffsetsToTxnRequest,
        generated.add_offsets_to_txn_response.AddOffsetsToTxnResponse,
        generated.add_partitions_to_txn_request.AddPartitionsToTxnRequest,
        generated.add_partitions_to_txn_response.AddPartitionsToTxnResponse,
        generated.add_raft_voter_request.AddRaftVoterRequest,
        generated.add_raft_voter_response.AddRaftVoterResponse,
        generated.allocate_producer_ids_request.AllocateProducerIdsRequest,
        generated.allocate_producer_ids_response.AllocateProducerIdsResponse,
        generated.alter_client_quotas_request.AlterClientQuotasRequest,
        generated.alter_client_quotas_response.AlterClientQuotasResponse,
        generated.alter_configs_request.AlterConfigsRequest,
        generated.alter_configs_response.AlterConfigsResponse,
        generated.alter_partition_reassignments_request.AlterPartitionReassignmentsRequest,
        generated.alter_partition_reassignments_response.AlterPartitionReassignmentsResponse,
        generated.alter_partition_request.AlterPartitionRequest,
        generated.alter_partition_response.AlterPartitionResponse,
        generated.alter_replica_log_dirs_request.AlterReplicaLogDirsRequest,
        generated.alter_replica_log_dirs_response.AlterReplicaLogDirsResponse,
        generated.alter_user_scram_credentials_request.AlterUserScramCredentialsRequest,
        generated.alter_user_scram_credentials_response.AlterUserScramCredentialsResponse,
        generated.api_versions_request.ApiVersionsRequest,
        generated.api_versions_response.ApiVersionsResponse,
        generated.assign_replicas_to_dirs_request.AssignReplicasToDirsRequest,
        generated.assign_replicas_to_dirs_response.AssignReplicasToDirsResponse,
        generated.automq_get_nodes_request.AutomqGetNodesRequest,
        generated.automq_get_nodes_response.AutomqGetNodesResponse,
        generated.automq_get_partition_snapshot_request.AutomqGetPartitionSnapshotRequest,
        generated.automq_get_partition_snapshot_response.AutomqGetPartitionSnapshotResponse,
        generated.automq_register_node_request.AutomqRegisterNodeRequest,
        generated.automq_register_node_response.AutomqRegisterNodeResponse,
        generated.automq_update_group_request.AutomqUpdateGroupRequest,
        generated.automq_update_group_response.AutomqUpdateGroupResponse,
        generated.automq_zone_router_request.AutomqZoneRouterRequest,
        generated.automq_zone_router_response.AutomqZoneRouterResponse,
        generated.begin_quorum_epoch_request.BeginQuorumEpochRequest,
        generated.begin_quorum_epoch_response.BeginQuorumEpochResponse,
        generated.broker_heartbeat_request.BrokerHeartbeatRequest,
        generated.broker_heartbeat_response.BrokerHeartbeatResponse,
        generated.broker_registration_request.BrokerRegistrationRequest,
        generated.broker_registration_response.BrokerRegistrationResponse,
        generated.close_streams_request.CloseStreamsRequest,
        generated.close_streams_response.CloseStreamsResponse,
        generated.commit_stream_object_request.CommitStreamObjectRequest,
        generated.commit_stream_object_response.CommitStreamObjectResponse,
        generated.commit_stream_set_object_request.CommitStreamSetObjectRequest,
        generated.commit_stream_set_object_response.CommitStreamSetObjectResponse,
        generated.consumer_group_describe_request.ConsumerGroupDescribeRequest,
        generated.consumer_group_describe_response.ConsumerGroupDescribeResponse,
        generated.consumer_group_heartbeat_request.ConsumerGroupHeartbeatRequest,
        generated.consumer_group_heartbeat_response.ConsumerGroupHeartbeatResponse,
        generated.consumer_protocol_assignment.ConsumerProtocolAssignment,
        generated.consumer_protocol_subscription.ConsumerProtocolSubscription,
        generated.controlled_shutdown_request.ControlledShutdownRequest,
        generated.controlled_shutdown_response.ControlledShutdownResponse,
        generated.controller_registration_request.ControllerRegistrationRequest,
        generated.controller_registration_response.ControllerRegistrationResponse,
        generated.create_acls_request.CreateAclsRequest,
        generated.create_acls_response.CreateAclsResponse,
        generated.create_delegation_token_request.CreateDelegationTokenRequest,
        generated.create_delegation_token_response.CreateDelegationTokenResponse,
        generated.create_partitions_request.CreatePartitionsRequest,
        generated.create_partitions_response.CreatePartitionsResponse,
        generated.create_streams_request.CreateStreamsRequest,
        generated.create_streams_response.CreateStreamsResponse,
        generated.create_topics_request.CreateTopicsRequest,
        generated.create_topics_response.CreateTopicsResponse,
        generated.default_principal_data.DefaultPrincipalData,
        generated.delete_acls_request.DeleteAclsRequest,
        generated.delete_acls_response.DeleteAclsResponse,
        generated.delete_groups_request.DeleteGroupsRequest,
        generated.delete_groups_response.DeleteGroupsResponse,
        generated.delete_k_vs_request.DeleteKVsRequest,
        generated.delete_k_vs_response.DeleteKVsResponse,
        generated.delete_records_request.DeleteRecordsRequest,
        generated.delete_records_response.DeleteRecordsResponse,
        generated.delete_share_group_state_request.DeleteShareGroupStateRequest,
        generated.delete_share_group_state_response.DeleteShareGroupStateResponse,
        generated.delete_streams_request.DeleteStreamsRequest,
        generated.delete_streams_response.DeleteStreamsResponse,
        generated.delete_topics_request.DeleteTopicsRequest,
        generated.delete_topics_response.DeleteTopicsResponse,
        generated.describe_acls_request.DescribeAclsRequest,
        generated.describe_acls_response.DescribeAclsResponse,
        generated.describe_client_quotas_request.DescribeClientQuotasRequest,
        generated.describe_client_quotas_response.DescribeClientQuotasResponse,
        generated.describe_cluster_request.DescribeClusterRequest,
        generated.describe_cluster_response.DescribeClusterResponse,
        generated.describe_configs_request.DescribeConfigsRequest,
        generated.describe_configs_response.DescribeConfigsResponse,
        generated.describe_delegation_token_request.DescribeDelegationTokenRequest,
        generated.describe_delegation_token_response.DescribeDelegationTokenResponse,
        generated.describe_groups_request.DescribeGroupsRequest,
        generated.describe_groups_response.DescribeGroupsResponse,
        generated.describe_license_request.DescribeLicenseRequest,
        generated.describe_license_response.DescribeLicenseResponse,
        generated.describe_log_dirs_request.DescribeLogDirsRequest,
        generated.describe_log_dirs_response.DescribeLogDirsResponse,
        generated.describe_producers_request.DescribeProducersRequest,
        generated.describe_producers_response.DescribeProducersResponse,
        generated.describe_quorum_request.DescribeQuorumRequest,
        generated.describe_quorum_response.DescribeQuorumResponse,
        generated.describe_streams_request.DescribeStreamsRequest,
        generated.describe_streams_response.DescribeStreamsResponse,
        generated.describe_topic_partitions_request.DescribeTopicPartitionsRequest,
        generated.describe_topic_partitions_response.DescribeTopicPartitionsResponse,
        generated.describe_transactions_request.DescribeTransactionsRequest,
        generated.describe_transactions_response.DescribeTransactionsResponse,
        generated.describe_user_scram_credentials_request.DescribeUserScramCredentialsRequest,
        generated.describe_user_scram_credentials_response.DescribeUserScramCredentialsResponse,
        generated.elect_leaders_request.ElectLeadersRequest,
        generated.elect_leaders_response.ElectLeadersResponse,
        generated.end_quorum_epoch_request.EndQuorumEpochRequest,
        generated.end_quorum_epoch_response.EndQuorumEpochResponse,
        generated.end_txn_request.EndTxnRequest,
        generated.end_txn_response.EndTxnResponse,
        generated.envelope_request.EnvelopeRequest,
        generated.envelope_response.EnvelopeResponse,
        generated.expire_delegation_token_request.ExpireDelegationTokenRequest,
        generated.expire_delegation_token_response.ExpireDelegationTokenResponse,
        generated.export_cluster_manifest_request.ExportClusterManifestRequest,
        generated.export_cluster_manifest_response.ExportClusterManifestResponse,
        generated.fetch_request.FetchRequest,
        generated.fetch_response.FetchResponse,
        generated.fetch_snapshot_request.FetchSnapshotRequest,
        generated.fetch_snapshot_response.FetchSnapshotResponse,
        generated.find_coordinator_request.FindCoordinatorRequest,
        generated.find_coordinator_response.FindCoordinatorResponse,
        generated.get_k_vs_request.GetKVsRequest,
        generated.get_k_vs_response.GetKVsResponse,
        generated.get_next_node_id_request.GetNextNodeIdRequest,
        generated.get_next_node_id_response.GetNextNodeIdResponse,
        generated.get_opening_streams_request.GetOpeningStreamsRequest,
        generated.get_opening_streams_response.GetOpeningStreamsResponse,
        generated.get_telemetry_subscriptions_request.GetTelemetrySubscriptionsRequest,
        generated.get_telemetry_subscriptions_response.GetTelemetrySubscriptionsResponse,
        generated.heartbeat_request.HeartbeatRequest,
        generated.heartbeat_response.HeartbeatResponse,
        generated.incremental_alter_configs_request.IncrementalAlterConfigsRequest,
        generated.incremental_alter_configs_response.IncrementalAlterConfigsResponse,
        generated.init_producer_id_request.InitProducerIdRequest,
        generated.init_producer_id_response.InitProducerIdResponse,
        generated.initialize_share_group_state_request.InitializeShareGroupStateRequest,
        generated.initialize_share_group_state_response.InitializeShareGroupStateResponse,
        generated.join_group_request.JoinGroupRequest,
        generated.join_group_response.JoinGroupResponse,
        generated.k_raft_version_record.KRaftVersionRecord,
        generated.leader_and_isr_request.LeaderAndIsrRequest,
        generated.leader_and_isr_response.LeaderAndIsrResponse,
        generated.leader_change_message.LeaderChangeMessage,
        generated.leave_group_request.LeaveGroupRequest,
        generated.leave_group_response.LeaveGroupResponse,
        generated.list_client_metrics_resources_request.ListClientMetricsResourcesRequest,
        generated.list_client_metrics_resources_response.ListClientMetricsResourcesResponse,
        generated.list_groups_request.ListGroupsRequest,
        generated.list_groups_response.ListGroupsResponse,
        generated.list_offsets_request.ListOffsetsRequest,
        generated.list_offsets_response.ListOffsetsResponse,
        generated.list_partition_reassignments_request.ListPartitionReassignmentsRequest,
        generated.list_partition_reassignments_response.ListPartitionReassignmentsResponse,
        generated.list_transactions_request.ListTransactionsRequest,
        generated.list_transactions_response.ListTransactionsResponse,
        generated.metadata_request.MetadataRequest,
        generated.metadata_response.MetadataResponse,
        generated.offset_commit_request.OffsetCommitRequest,
        generated.offset_commit_response.OffsetCommitResponse,
        generated.offset_delete_request.OffsetDeleteRequest,
        generated.offset_delete_response.OffsetDeleteResponse,
        generated.offset_fetch_request.OffsetFetchRequest,
        generated.offset_fetch_response.OffsetFetchResponse,
        generated.offset_for_leader_epoch_request.OffsetForLeaderEpochRequest,
        generated.offset_for_leader_epoch_response.OffsetForLeaderEpochResponse,
        generated.open_streams_request.OpenStreamsRequest,
        generated.open_streams_response.OpenStreamsResponse,
        generated.prepare_s3_object_request.PrepareS3ObjectRequest,
        generated.prepare_s3_object_response.PrepareS3ObjectResponse,
        generated.produce_request.ProduceRequest,
        generated.produce_response.ProduceResponse,
        generated.push_telemetry_request.PushTelemetryRequest,
        generated.push_telemetry_response.PushTelemetryResponse,
        generated.put_k_vs_request.PutKVsRequest,
        generated.put_k_vs_response.PutKVsResponse,
        generated.read_share_group_state_request.ReadShareGroupStateRequest,
        generated.read_share_group_state_response.ReadShareGroupStateResponse,
        generated.read_share_group_state_summary_request.ReadShareGroupStateSummaryRequest,
        generated.read_share_group_state_summary_response.ReadShareGroupStateSummaryResponse,
        generated.remove_raft_voter_request.RemoveRaftVoterRequest,
        generated.remove_raft_voter_response.RemoveRaftVoterResponse,
        generated.renew_delegation_token_request.RenewDelegationTokenRequest,
        generated.renew_delegation_token_response.RenewDelegationTokenResponse,
        generated.request_header.RequestHeader,
        generated.response_header.ResponseHeader,
        generated.sasl_authenticate_request.SaslAuthenticateRequest,
        generated.sasl_authenticate_response.SaslAuthenticateResponse,
        generated.sasl_handshake_request.SaslHandshakeRequest,
        generated.sasl_handshake_response.SaslHandshakeResponse,
        generated.share_acknowledge_request.ShareAcknowledgeRequest,
        generated.share_acknowledge_response.ShareAcknowledgeResponse,
        generated.share_fetch_request.ShareFetchRequest,
        generated.share_fetch_response.ShareFetchResponse,
        generated.share_group_describe_request.ShareGroupDescribeRequest,
        generated.share_group_describe_response.ShareGroupDescribeResponse,
        generated.share_group_heartbeat_request.ShareGroupHeartbeatRequest,
        generated.share_group_heartbeat_response.ShareGroupHeartbeatResponse,
        generated.snapshot_footer_record.SnapshotFooterRecord,
        generated.snapshot_header_record.SnapshotHeaderRecord,
        generated.stop_replica_request.StopReplicaRequest,
        generated.stop_replica_response.StopReplicaResponse,
        generated.sync_group_request.SyncGroupRequest,
        generated.sync_group_response.SyncGroupResponse,
        generated.trim_streams_request.TrimStreamsRequest,
        generated.trim_streams_response.TrimStreamsResponse,
        generated.txn_offset_commit_request.TxnOffsetCommitRequest,
        generated.txn_offset_commit_response.TxnOffsetCommitResponse,
        generated.unregister_broker_request.UnregisterBrokerRequest,
        generated.unregister_broker_response.UnregisterBrokerResponse,
        generated.update_features_request.UpdateFeaturesRequest,
        generated.update_features_response.UpdateFeaturesResponse,
        generated.update_license_request.UpdateLicenseRequest,
        generated.update_license_response.UpdateLicenseResponse,
        generated.update_metadata_request.UpdateMetadataRequest,
        generated.update_metadata_response.UpdateMetadataResponse,
        generated.update_raft_voter_request.UpdateRaftVoterRequest,
        generated.update_raft_voter_response.UpdateRaftVoterResponse,
        generated.vote_request.VoteRequest,
        generated.vote_response.VoteResponse,
        generated.voters_record.VotersRecord,
        generated.write_share_group_state_request.WriteShareGroupStateRequest,
        generated.write_share_group_state_response.WriteShareGroupStateResponse,
        generated.write_txn_markers_request.WriteTxnMarkersRequest,
        generated.write_txn_markers_response.WriteTxnMarkersResponse,
    };

    inline for (messages) |Message| {
        try roundTripDefaultVersions(Message);
    }
}
